apiVersion: v1
kind: Service
metadata:
  name: {{ include "tor-obfs4-bridge.fullname" . }}
  labels:
    {{- include "tor-obfs4-bridge.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- if eq .Values.service.type "LoadBalancer" }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy | default "Local" }}
  {{- end }}
  ports:
    - name: orport
      port: {{ .Values.config.orPort }}
      targetPort: orport
      protocol: TCP
    - name: ptport
      port: {{ .Values.config.ptPort }}
      targetPort: ptport
      protocol: TCP
  selector:
    {{- include "tor-obfs4-bridge.selectorLabels" . | nindent 4 }}
